services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - APP_URL=http://127.0.0.1:6875
      - APP_KEY=${APP_KEY}
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=bookstack
    volumes:
      - data:/config
    ports:
      - 6875:80
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    external: true
    name: base
